#!/bin/bash                                                                                                        
# count how many updates we have got
updates=$(/usr/lib/update-notifier/apt-check 2>&1)
non_security_updates=$(echo "$updates" | cut -d ";" -f 1)
security_updates=$(echo "$updates" | cut -d ";" -f 2)

RED="\[\e[38;5;196m\]"


#ups=`/usr/lib/update-notifier/apt-check --human-readable | head -1 | awk '{print $1;}'`

# print the results
if [ "$security_updates" -gt "1" ] && [ "$non_security_updates" -gt "1" ]
then
    echo "  $security_updates  $non_security_updates "

elif [ "$security_updates" -gt "1" ] || [ "$security_updates" -eq "1" ]
then
    echo "   $security_updates "

elif [ "$non_security_updates" -gt "1" ] || [ "$non_security_updates" -eq "1" ]
then
    echo "   $non_security_updates "

else
    echo " ♥ "
fi
